#!/bin/bash

hostname=$(hostname)

if [ "$hostname" = "rocks-test.local" ];then
  for i in 0 1 2 3 4
  do
    ssh -t compute-0-$i 'pkill runcfd' 
  done
elif [ "$hostname" = "compute-0-1.local" ]||[ "$hostname" = "compute-0-2.local" ]||[ "$hostname" = "compute-0-2.local" ]||[ "$hostname" = "compute-0-3.local" ]||[ "$hostname" = "compute-0-4.local" ];then
  ssh -t rocks-test.local 'serialkiller' 
else
  pkill runcfd
fi

